# Generated by Django 4.0.5 on 2022-06-25 22:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('Last_name', models.CharField(default='', max_length=60)),
                ('State', models.BooleanField(default=True)),
                ('Role', models.CharField(max_length=51)),
                ('Email', models.CharField(max_length=510)),
                ('Password', models.CharField(max_length=255)),
                ('Phone', models.CharField(default='', max_length=16)),
                ('Media_file', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
    ]
