# Generated by Django 4.0.5 on 2022-06-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('State', models.BooleanField(default=True)),
                ('Role', models.CharField(max_length=51)),
                ('Email', models.CharField(max_length=510)),
                ('Password', models.CharField(max_length=255)),
                ('Phone', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
