# Generated by Django 4.0.5 on 2022-06-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Details', models.CharField(blank=True, max_length=500, null=True)),
                ('State', models.CharField(max_length=20)),
                ('Space', models.CharField(blank=True, max_length=200, null=True)),
                ('Cost', models.IntegerField(default=0)),
                ('Media_file', models.ImageField(blank=True, null=True, upload_to='images_events/')),
                ('Start_date', models.DateField()),
                ('Finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Value', models.IntegerField()),
                ('pay_method', models.CharField(max_length=30)),
                ('ID_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
