# Generated by Django 4.0.4 on 2022-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=120)),
                ('State', models.BooleanField(default=True)),
                ('Role', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
