# Generated by Django 4.0.5 on 2022-06-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Init_hour', models.TimeField()),
                ('Final_hour', models.TimeField()),
                ('Space', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=51)),
                ('Details', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Details', models.CharField(max_length=51)),
                ('State', models.CharField(max_length=20)),
                ('Space', models.CharField(max_length=20)),
                ('Cost', models.IntegerField(default=0)),
                ('Media_file', models.ImageField(upload_to='images_events/')),
                ('Date', models.DateField()),
                ('Init_hour', models.TimeField()),
                ('Final_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('State', models.BooleanField(default=True)),
                ('Role', models.CharField(max_length=51)),
                ('Email', models.CharField(max_length=510)),
                ('Password', models.CharField(max_length=255)),
                ('Phone', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Value', models.IntegerField()),
                ('pay_method', models.CharField(max_length=30)),
                ('ID_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Summary', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=20)),
                ('Media_file', models.FileField(upload_to='images_videos_news/')),
                ('Edition_date', models.DateField()),
                ('ID_EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ID_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled_in_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.activity')),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='ID_Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
