# Generated by Django 4.0.4 on 2022-06-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Init_hour', models.TimeField()),
                ('Final_hour', models.TimeField()),
                ('Space', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Details', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=20)),
                ('Space', models.CharField(max_length=20)),
                ('Media_file', models.ImageField(upload_to='images_videos')),
                ('Date', models.DateField()),
                ('Init_hour', models.TimeField()),
                ('Final_hour', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Value', models.IntegerField()),
                ('pay_method', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Summary', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=20)),
                ('Media_file', models.FileField(upload_to='images_videos')),
                ('Edition_date', models.DateField()),
                ('ID_EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ID_USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='event_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ID_Payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.payment')),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled_in_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.activity')),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='ID_Event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
