# Generated by Django 4.0.4 on 2022-06-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='ID_EVENT',
            new_name='id_event',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='ID_USER',
            new_name='id_user',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
