# Generated by Django 4.0.5 on 2022-06-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Media_file',
            field=models.ImageField(blank=True, null=True, upload_to='images_events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Space',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
