# Generated by Django 4.0.4 on 2022-06-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='id_event',
            new_name='ID_event',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='id_user',
            new_name='ID_user',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
