# Generated by Django 4.0.5 on 2022-06-13 02:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_news_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Media_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
