# Generated by Django 4.0.5 on 2022-06-13 03:09

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_news_media_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Date',
            new_name='Finish_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Final_hour',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Init_hour',
        ),
        migrations.AddField(
            model_name='event',
            name='Start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Media_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
