# Generated by Django 4.0.5 on 2022-06-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_date_event_finish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Finish_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Media_file',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Start_date',
        ),
    ]
