# Generated by Django 4.0.5 on 2022-06-13 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Finish_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
