# Generated by Django 4.0.5 on 2022-06-13 15:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Media_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Details',
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
    ]
