# Generated by Django 4.0.5 on 2022-06-13 15:49

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_media_file_alter_event_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Media_file',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
