# Generated by Django 4.0.5 on 2022-06-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_enrolled_in_activity_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled_in_activity',
            name='ID_activity',
        ),
        migrations.RemoveField(
            model_name='enrolled_in_activity',
            name='ID_user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='ID_event',
        ),
        migrations.RemoveField(
            model_name='news',
            name='ID_user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Enrolled_in_activity',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
