# Generated by Django 4.0.5 on 2022-06-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Hora_inicio', models.TimeField()),
                ('Hora_finalizacion', models.TimeField()),
                ('Espacio', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('Detalles', models.CharField(max_length=100)),
                ('Titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Detalles', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=20)),
                ('Espacio', models.CharField(max_length=20)),
                ('Media_file', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Hora_inicio', models.TimeField()),
                ('Hora_finalizacion', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Valor', models.IntegerField()),
                ('Metodo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='Telefono',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.CreateModel(
            name='Pago_de_evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('ID_Pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.pago')),
                ('ID_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Resumen', models.CharField(max_length=255)),
                ('Estado', models.CharField(max_length=20)),
                ('Media_file', models.CharField(max_length=200)),
                ('Fecha_edicion', models.DateField()),
                ('ID_EVENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
                ('ID_USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inscritos_a_actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.actividad')),
                ('ID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='ID_Evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
