# Generated by Django 4.0.5 on 2022-06-25 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Init_hour', models.TimeField()),
                ('Final_hour', models.TimeField()),
                ('Space', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=51)),
                ('Details', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('ID_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
