# Generated by Django 4.0.5 on 2022-07-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Capacity',
            field=models.IntegerField(default=100),
        ),
    ]
