# Generated by Django 4.0.5 on 2022-07-08 22:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media_file', cloudinary.models.CloudinaryField(max_length=255)),
                ('ID_Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ID_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
